language: python
python:
  - "2.7"

# command to install dependencies

install: 
  - pip install requests
  - pip install responses
  - pip install coveralls
  - pip install pytest-cov
# command to run tests
script: 
  coverage run -m py.test

after_success:
  coveralls