language: python
python:
  - "2.7"

# command to install dependencies

install: 
  - pip install requests
  - pip install responses
  - pip install python-coveralls
# command to run tests
script:
  - py.test mobilvest/test_mobilvest.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after_success:
  coveralls
